### ISSUE TITLE
Require click on empty block of time same as event tap

### ISSUE THREAD

**Issue by deepbhavsar** [Skyost/FlutterWeekView#22] opened 2020-04-15 10:06 UTC
DayView and WeekView should allow user to click on empty block of time. User can same way add the event by tapping on it.
Let me know whether you like this idea or not. I have check ios calendar app where they are allowing same.
Thank you

**Comment by Skyost** [comment] 2020-04-15 10:20
I think it's pretty related to #19 ?

**Comment by Skyost** [comment] 2020-05-12 09:00
Closed as duplicate of #19.

**Comment by FlammerSL** [comment] 2020-12-02 19:11
Hi Skyost,

I think this is not the same as #19, if we can have a callback from the time slot which the user clecked, it will be a good addition to this. This is not about hour column callback.

**Comment by gabrielbertollo** [comment] 2021-07-14 21:00
> Hi Skyost,
> 
> I think this is not the same as #19, if we can have a callback from the time slot which the user clecked, it will be a good addition to this. This is not about hour column callback.

Hi @Skyost . I agree with this. Would really help if we could have a callback on the actual hour row. Let me know if you think it is possible.

Thank you.

**Comment by Skyost** [comment] 2021-07-22 15:19
I'm gonna check what I can do :wink:

**Comment by AyshaHamna** [comment] 2021-09-21 06:10
> Hi Skyost,
> 
> I think this is not the same as #19, if we can have a callback from the time slot which the user clecked, it will be a good addition to this. This is not about hour column callback.



> DayView and WeekView should allow user to click on empty block of time. User can same way add the event by tapping on it.
> Let me know whether you like this idea or not. I have check ios calendar app where they are allowing same.
> Thank you

Agree. this would be user-friendly and more comfortable to use. clicking on a block and adding an event is simple and easy

**Comment by Skyost** [comment] 2021-09-27 17:46
Agreed. Sadly, I don't have the time to work on this for the moment, but feel free to submit your pull requests !

**Closed** 2023-02-16 17:40 UTC
Labels: enhancement
