### ISSUE TITLE
Scroll to specific time

### ISSUE THREAD

**Issue by caiogranero** [Skyost/FlutterWeekView#47] opened 2020-07-08 10:48 UTC
Hello,

it will be a nice feature if `DayViewController` have a option to scroll the screen to a current time. I know we can scroll to currentTime when the widget build but i would like to do this in any other moment.

In version 0.2.1+6 i did this (i had fixed hourRowHeight, so it was easier to solve my problem):

```
class CalendarDayViewController extends DayViewController {
  /// Returns whether this widget should be zoomable.
  /// Calculates the top offset of a given hour and a given minute.
  double calculateTopOffset(int hour, [int minute = 0, double hourRowHeight]) =>
      (hour + (minute / 60)) * (hourRowHeight ?? 127);

  /// Scrolls to a given time if possible.
  void scrollToTime(int hour, int minute) {
    double topOffset = calculateTopOffset(hour, minute);
    verticalScrollController.animateTo(math.min(topOffset, verticalScrollController.position.maxScrollExtent), duration: Duration(milliseconds: 750), curve: Curves.easeInOut);
  }
}
```

But now, DayViewController doesn't have the verticalScrollController property, so i can't do this anymore.

What do you think?

**Comment by Skyost** [comment] 2020-07-08 15:19
@caiogranero Is this a duplicate of #38 ?

**Comment by caiogranero** [comment] 2020-07-09 13:04
I think so, i will wait for this feature. thank you.

**Closed** 2020-07-09 13:04 UTC
Labels: enhancement
