### ISSUE TITLE
Ability to scroll by one item in WeekView.

### ISSUE THREAD

**Issue by hmarat** [Skyost/FlutterWeekView#81] opened 2021-09-22 08:12 UTC
When you scroll week view's current day, it can scroll by more than one item(maybe 2, 3, or even 4). So it would be cool to set an option, so user could only scroll by one item (previous day and next day). Thank you.

**Comment by Skyost** [comment] 2021-09-27 17:44
Seems to be a duplicate of #79, isn't it ?

**Closed** 2023-03-15 12:29 UTC
Labels: enhancement
